# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release

on:
  push:
    tags:
      - "v*"

permissions: write-all

jobs:
  build:
    name: Build and release sql web cli
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2

      - name: Install Spin
        uses: fermyon/actions/spin/setup@v1
        with:
          plugins: js2wasm

      - name: Build sql cli
        shell: bash
        run: |
          npm install
          spin build
      
      - name: set the release version (tag)
        run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      
      - name: generate checksums
        run: |
          sha256sum target/spin-sqlite-web-cli.wasm > checksums-${{ env.RELEASE_VERSION }}.txt

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            target/spin-sqlite-web-cli.wasm
            checksums-${{ env.RELEASE_VERSION }}.txt
